/*
 * SupplierTree.java
 *
 * Created on 18 de agosto de 2008, 11:25 AM
 */

package interfacegraphicsuppliers;

import conectivity.ConnectSuppliers;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.TreeCellRenderer;
import treeConfiguration.treeIcon.IconCellRenderer;
import utilities.Utils;

/**
 *
 * @author  Elvin Gregorio
 */
public class SupplierTree extends javax.swing.JInternalFrame {
    private static String NameSupplier = null;
    
    /** Creates new form SupplierTree */
    public SupplierTree() {
        initComponents();
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/images/WindowsExplorer.png")));
        TreeProveedor.setModel(ConnectSuppliers.LoadSuppliersTree());               
        TreeCellRenderer renderer = new IconCellRenderer();
        TreeProveedor.setCellRenderer(renderer);
        TreeProveedor.setShowsRootHandles(true);   
        TreeProveedor.addTreeSelectionListener(new TreeSelectionListener() 
        {
         public void valueChanged(TreeSelectionEvent e)
         {
         DefaultMutableTreeNode Nodo = (DefaultMutableTreeNode)(e.getPath().getLastPathComponent());
         Object NameNodo = Nodo.getUserObject();
         
         if(Nodo.isLeaf())
             {              
               setNameSupplier(String.valueOf(NameNodo));
               LCodProveedor.setText("Cód Proveedor: "+ConnectSuppliers.getCodSuppliers(getNameSupplier()));
             }
         }     
        });
        }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMain = new javax.swing.JPanel();
        ScrollPane = new javax.swing.JScrollPane();
        TreeProveedor = new javax.swing.JTree();
        BAceptar = new javax.swing.JButton();
        BCancelar = new javax.swing.JButton();
        LCodProveedor = new javax.swing.JLabel();
        LBLfondo = new javax.swing.JLabel();

        setTitle("Búsqueda de Proveedor");

        PanelMain.setLayout(null);

        ScrollPane.setForeground(new java.awt.Color(0, 0, 204));

        TreeProveedor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TreeProveedor.setFont(new java.awt.Font("Verdana", 1, 12));
        TreeProveedor.setForeground(new java.awt.Color(0, 0, 204));
        ScrollPane.setViewportView(TreeProveedor);

        PanelMain.add(ScrollPane);
        ScrollPane.setBounds(0, 0, 210, 190);

        BAceptar.setFont(new java.awt.Font("BankGothic Lt BT", 1, 12));
        BAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aceptar.png"))); // NOI18N
        BAceptar.setText("Aceptar");
        BAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAceptarActionPerformed(evt);
            }
        });
        PanelMain.add(BAceptar);
        BAceptar.setBounds(225, 40, 120, 30);

        BCancelar.setFont(new java.awt.Font("BankGothic Lt BT", 1, 12));
        BCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancelar.png"))); // NOI18N
        BCancelar.setLabel("Cancelar");
        BCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCancelarActionPerformed(evt);
            }
        });
        PanelMain.add(BCancelar);
        BCancelar.setBounds(225, 90, 120, 30);

        LCodProveedor.setFont(new java.awt.Font("Verdana", 1, 12));
        LCodProveedor.setForeground(new java.awt.Color(0, 0, 204));
        LCodProveedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PanelMain.add(LCodProveedor);
        LCodProveedor.setBounds(210, 150, 150, 30);

        LBLfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shell_bar.png"))); // NOI18N
        LBLfondo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelMain.add(LBLfondo);
        LBLfondo.setBounds(190, 0, 190, 190);

        getContentPane().add(PanelMain, java.awt.BorderLayout.CENTER);

        setBounds(100, 100, 375, 218);
    }// </editor-fold>//GEN-END:initComponents

    private void BAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAceptarActionPerformed
        if(getNameSupplier() == null) 
        {
            Utils.MyDialog("Selecione a un Empleado","Información del Sistema","Error.png","Infected.wav");
        } 
        else 
        {
            this.dispose();
            ConnectSuppliers.LoadSupplierDataSearch(ConnectSuppliers.getCodSuppliers(getNameSupplier()));
            JSuppliers.setCodSupplier(ConnectSuppliers.getCodSuppliers(getNameSupplier()));
            JSuppliers.BActualizar.setEnabled(true);
        }
    }//GEN-LAST:event_BAceptarActionPerformed

     public static String getNameSupplier()
   {
    return NameSupplier;
   }
    public void setNameSupplier(String name)
    {
        this.NameSupplier = name;
    }
    
    private void BCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCancelarActionPerformed
        this.dispose();
//        setNameEmployee(null);
    }//GEN-LAST:event_BCancelarActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAceptar;
    private javax.swing.JButton BCancelar;
    private javax.swing.JLabel LBLfondo;
    private javax.swing.JLabel LCodProveedor;
    private javax.swing.JPanel PanelMain;
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JTree TreeProveedor;
    // End of variables declaration//GEN-END:variables
    
}
