/*
 * DeleteProduct.java
 *
 * Created on 20 de agosto de 2008, 01:11 AM
 */

package interfacegraphic.products;

import conectivity.ConnectProducts;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import utilities.Utils;

/**
 *
 * @author  Elvin Gregorio
 */
public class DeleteProduct extends javax.swing.JInternalFrame {
    
    /** Creates new form DeleteProduct */
    public DeleteProduct() {
        initComponents();
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editdelete.png")));
        ConnectProducts.LoadProductsCombo();  
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panelfondo = new javax.swing.JPanel();
        lblselccionempleado = new javax.swing.JLabel();
        Comboproducto = new javax.swing.JComboBox();
        BAceptar = new javax.swing.JButton();
        BCancelar = new javax.swing.JButton();
        lblfondo1 = new javax.swing.JLabel();

        setTitle("Dar de Baja a un Producto");

        Panelfondo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Panelfondo.setLayout(null);

        lblselccionempleado.setFont(new java.awt.Font("BankGothic Lt BT", 1, 12));
        lblselccionempleado.setText("Seleccione el Producto");
        Panelfondo.add(lblselccionempleado);
        lblselccionempleado.setBounds(15, 10, 174, 25);

        Panelfondo.add(Comboproducto);
        Comboproducto.setBounds(15, 50, 170, 25);

        BAceptar.setFont(new java.awt.Font("BankGothic Lt BT", 1, 12));
        BAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aceptar.png"))); // NOI18N
        BAceptar.setText("Aceptar");
        BAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAceptarActionPerformed(evt);
            }
        });
        Panelfondo.add(BAceptar);
        BAceptar.setBounds(200, 10, 120, 30);

        BCancelar.setFont(new java.awt.Font("BankGothic Lt BT", 1, 12));
        BCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancelar.png"))); // NOI18N
        BCancelar.setText("Cancelar");
        BCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCancelarActionPerformed(evt);
            }
        });
        Panelfondo.add(BCancelar);
        BCancelar.setBounds(200, 50, 120, 30);

        lblfondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shell_bar.png"))); // NOI18N
        Panelfondo.add(lblfondo1);
        lblfondo1.setBounds(0, 0, 330, 120);

        getContentPane().add(Panelfondo, java.awt.BorderLayout.CENTER);

        setBounds(100, 100, 344, 114);
    }// </editor-fold>//GEN-END:initComponents

    private void BAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAceptarActionPerformed
        String objButtons[] = {"Si","No"};
        Utils.PlaySound("popUp.wav");
        int message = JOptionPane.showOptionDialog(this, "Está Seguro de Despedir a esta persona??", "JPharmware_2.0", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE,
                new ImageIcon(getClass().getResource("/images/dialogs/Interrogacion.png")), objButtons, objButtons[1]);
        
        if(message == 0) {
//            int CodProd = ConnectProducts.getCodProducto(String.valueOf(Comboproducto.getSelectedItem()));
//            ConnectProducts.LoadDataSearch(CodProd);
//            ConnectProducts.DeleteProduct(CodProd);
            this.dispose();
        } else
            this.setDefaultCloseOperation(JInternalFrame.DO_NOTHING_ON_CLOSE);
    }//GEN-LAST:event_BAceptarActionPerformed

    private void BCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_BCancelarActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAceptar;
    private javax.swing.JButton BCancelar;
    public static javax.swing.JComboBox Comboproducto;
    private javax.swing.JPanel Panelfondo;
    private javax.swing.JLabel lblfondo1;
    private javax.swing.JLabel lblselccionempleado;
    // End of variables declaration//GEN-END:variables
    
}
