/*
 * JProducts.java
 *
 * Created on 18 de agosto de 2008, 11:23 PM
 */

package interfacegraphic.products;

import conectivity.ConnectProducts;
import interfacegraphic.PanelEmperador;
import java.awt.event.KeyEvent;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import utilities.Utils;

/**
 *
 * @author  Elvin Gregorio
 */
public class JProducts extends javax.swing.JInternalFrame {
    private static String NombreProducto;
    private static String Lote;
    private static String DetallePresentacion;
    private static String UndsContenido;
    private static String PrecioVta;
    private static int CodCategoria, CodProducto;
    public static Calendar calendar;
    
    /** Creates new form JProducts */
    public JProducts() {
        initComponents();
//        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fullbasket.png")));
        ConnectProducts.LoadProductData();
        ConnectProducts.CargarComboCategoria();
        TablaProductos.packAll();
        BActualizar.setEnabled(false);

    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DesktopProduct = new javax.swing.JDesktopPane();
        TabbedPane = new javax.swing.JTabbedPane();
        Pane0 = new javax.swing.JPanel();
        PanelDatos = new javax.swing.JPanel();
        LNombreProducto = new javax.swing.JLabel();
        LNumRuc = new javax.swing.JLabel();
        LLote = new javax.swing.JLabel();
        TNombreProducto = new javax.swing.JTextField();
        TLote = new javax.swing.JTextField();
        Combocategoria = new javax.swing.JComboBox();
        LPresentacion = new javax.swing.JLabel();
        TPresentacion = new javax.swing.JTextField();
        LUnds = new javax.swing.JLabel();
        TUnds = new javax.swing.JTextField();
        BAgregar = new javax.swing.JButton();
        BActualizar = new javax.swing.JButton();
        LPrecioVta = new javax.swing.JLabel();
        TPrecioVta = new javax.swing.JTextField();
        PanelDatos1 = new javax.swing.JPanel();
        ScrollPane1 = new javax.swing.JScrollPane();
        TablaProductos = new org.jdesktop.swingx.JXTable();
        LblProductos = new javax.swing.JLabel();
        lblfondo = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        DesktopProduct1 = new javax.swing.JDesktopPane();
        TabbedPane1 = new javax.swing.JTabbedPane();
        Pane1 = new javax.swing.JPanel();
        PanelDatos2 = new javax.swing.JPanel();
        LNombreProducto1 = new javax.swing.JLabel();
        LNumRuc1 = new javax.swing.JLabel();
        LLote1 = new javax.swing.JLabel();
        TNombreProducto1 = new javax.swing.JTextField();
        TLote1 = new javax.swing.JTextField();
        Combocategoria1 = new javax.swing.JComboBox();
        LPresentacion1 = new javax.swing.JLabel();
        TPresentacion1 = new javax.swing.JTextField();
        LUnds1 = new javax.swing.JLabel();
        TUnds1 = new javax.swing.JTextField();
        BAgregar1 = new javax.swing.JButton();
        BActualizar1 = new javax.swing.JButton();
        LPrecioVta1 = new javax.swing.JLabel();
        TPrecioVta1 = new javax.swing.JTextField();
        PanelDatos3 = new javax.swing.JPanel();
        ScrollPane2 = new javax.swing.JScrollPane();
        TablaProductos1 = new org.jdesktop.swingx.JXTable();
        LblProductos1 = new javax.swing.JLabel();
        lblfondo1 = new javax.swing.JLabel();
        MenuBar1 = new javax.swing.JMenuBar();
        MArchivo1 = new javax.swing.JMenu();
        MINuevo1 = new javax.swing.JMenuItem();
        MIDarBaja1 = new javax.swing.JMenuItem();
        MICargos1 = new javax.swing.JMenuItem();
        MISalir1 = new javax.swing.JMenuItem();
        MenuBar = new javax.swing.JMenuBar();
        MArchivo = new javax.swing.JMenu();
        MINuevo = new javax.swing.JMenuItem();
        MIDarBaja = new javax.swing.JMenuItem();
        MICargos = new javax.swing.JMenuItem();
        MISalir = new javax.swing.JMenuItem();

        setTitle("Administración Productos Farmacia \"Allison\"");
        getContentPane().setLayout(null);

        DesktopProduct.setBackground(java.awt.SystemColor.control);
        DesktopProduct.setOpaque(false);

        TabbedPane.setForeground(new java.awt.Color(0, 0, 204));
        TabbedPane.setFont(new java.awt.Font("BankGothic Lt BT", 1, 12));

        Pane0.setFont(new java.awt.Font("BankGothic Lt BT", 1, 12));
        Pane0.setLayout(null);

        PanelDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos Generales", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("BankGothic Lt BT", 1, 12), new java.awt.Color(0, 0, 204)));
        PanelDatos.setOpaque(false);
        PanelDatos.setLayout(null);

        LNombreProducto.setFont(new java.awt.Font("Verdana", 1, 12));
        LNombreProducto.setText("Nombre Producto");
        PanelDatos.add(LNombreProducto);
        LNombreProducto.setBounds(10, 30, 130, 25);

        LNumRuc.setFont(new java.awt.Font("Verdana", 1, 12));
        LNumRuc.setText("Categoría");
        PanelDatos.add(LNumRuc);
        LNumRuc.setBounds(365, 30, 64, 25);

        LLote.setFont(new java.awt.Font("Verdana", 1, 12));
        LLote.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LLote.setText("Presentación de Lote");
        PanelDatos.add(LLote);
        LLote.setBounds(10, 80, 140, 25);

        TNombreProducto.setFont(new java.awt.Font("Verdana", 1, 10));
        TNombreProducto.setForeground(new java.awt.Color(0, 102, 0));
        TNombreProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TNombreProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TNombreProductoKeyTyped(evt);
            }
        });
        PanelDatos.add(TNombreProducto);
        TNombreProducto.setBounds(160, 30, 190, 25);

        TLote.setFont(new java.awt.Font("Verdana", 1, 10));
        TLote.setForeground(new java.awt.Color(0, 102, 0));
        TLote.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TLote.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TLoteKeyTyped(evt);
            }
        });
        PanelDatos.add(TLote);
        TLote.setBounds(160, 80, 190, 25);

        Combocategoria.setFont(new java.awt.Font("Verdana", 1, 10));
        Combocategoria.setForeground(new java.awt.Color(0, 102, 0));
        Combocategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hola" }));
        PanelDatos.add(Combocategoria);
        Combocategoria.setBounds(480, 30, 150, 25);

        LPresentacion.setFont(new java.awt.Font("Verdana", 1, 12));
        LPresentacion.setText("Detalle Producto");
        PanelDatos.add(LPresentacion);
        LPresentacion.setBounds(365, 80, 110, 25);

        TPresentacion.setFont(new java.awt.Font("Verdana", 1, 10));
        TPresentacion.setForeground(new java.awt.Color(0, 102, 0));
        TPresentacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TPresentacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TPresentacionKeyTyped(evt);
            }
        });
        PanelDatos.add(TPresentacion);
        TPresentacion.setBounds(480, 80, 150, 25);

        LUnds.setFont(new java.awt.Font("Verdana", 1, 12));
        LUnds.setText("Unidades por Lote");
        PanelDatos.add(LUnds);
        LUnds.setBounds(10, 130, 140, 25);

        TUnds.setFont(new java.awt.Font("Verdana", 1, 10));
        TUnds.setForeground(new java.awt.Color(0, 102, 0));
        TUnds.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TUnds.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TUndsKeyTyped(evt);
            }
        });
        PanelDatos.add(TUnds);
        TUnds.setBounds(160, 130, 190, 25);

        BAgregar.setFont(new java.awt.Font("BankGothic Lt BT", 1, 12));
        BAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        BAgregar.setText("Agregar");
        BAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAgregarActionPerformed(evt);
            }
        });
        PanelDatos.add(BAgregar);
        BAgregar.setBounds(150, 170, 135, 30);

        BActualizar.setFont(new java.awt.Font("BankGothic Lt BT", 1, 12));
        BActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh16.png"))); // NOI18N
        BActualizar.setText("Actualizar");
        BActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BActualizarActionPerformed(evt);
            }
        });
        PanelDatos.add(BActualizar);
        BActualizar.setBounds(340, 170, 135, 30);

        LPrecioVta.setFont(new java.awt.Font("Verdana", 1, 12));
        LPrecioVta.setText("Precio Venta");
        PanelDatos.add(LPrecioVta);
        LPrecioVta.setBounds(365, 130, 90, 25);

        TPrecioVta.setFont(new java.awt.Font("Verdana", 1, 10));
        TPrecioVta.setForeground(new java.awt.Color(0, 102, 0));
        TPrecioVta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TPrecioVta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TPrecioVtaKeyTyped(evt);
            }
        });
        PanelDatos.add(TPrecioVta);
        TPrecioVta.setBounds(480, 130, 150, 25);

        Pane0.add(PanelDatos);
        PanelDatos.setBounds(10, 10, 640, 210);

        PanelDatos1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Lista de Productos Farmacia \"Allison\"", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("BankGothic Lt BT", 1, 12), new java.awt.Color(0, 0, 204)));
        PanelDatos1.setOpaque(false);
        PanelDatos1.setLayout(null);

        TablaProductos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Producto", "Presentación Lote", "Detalle Producto", "Unidades por Lote", "Categoría", "Precio de Venta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaProductos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        TablaProductos.setCellSelectionEnabled(true);
        TablaProductos.setColumnControlVisible(true);
        TablaProductos.setColumnMargin(10);
        TablaProductos.setEditable(false);
        TablaProductos.setFont(new java.awt.Font("Verdana", 0, 10));
        ScrollPane1.setViewportView(TablaProductos);

        PanelDatos1.add(ScrollPane1);
        ScrollPane1.setBounds(10, 60, 620, 200);

        LblProductos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/titles/ProductosLogo.png"))); // NOI18N
        PanelDatos1.add(LblProductos);
        LblProductos.setBounds(0, 0, 630, 60);

        Pane0.add(PanelDatos1);
        PanelDatos1.setBounds(10, 230, 640, 270);

        lblfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wallpapers/shell_bar.png"))); // NOI18N
        Pane0.add(lblfondo);
        lblfondo.setBounds(0, 0, 650, 500);

        TabbedPane.addTab("Productos", new javax.swing.ImageIcon(getClass().getResource("/images/drugbasket.png")), Pane0); // NOI18N

        TabbedPane.setBounds(0, 0, 670, 540);
        DesktopProduct.add(TabbedPane, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(DesktopProduct);
        DesktopProduct.setBounds(0, 0, 660, 530);

        jInternalFrame1.setTitle("Administración Productos Farmacia \"Allison\"");
        jInternalFrame1.getContentPane().setLayout(null);

        DesktopProduct1.setBackground(java.awt.SystemColor.control);
        DesktopProduct1.setOpaque(false);

        TabbedPane1.setForeground(new java.awt.Color(0, 0, 204));
        TabbedPane1.setFont(new java.awt.Font("BankGothic Lt BT", 1, 12));

        Pane1.setFont(new java.awt.Font("BankGothic Lt BT", 1, 12));
        Pane1.setLayout(null);

        PanelDatos2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos Generales", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("BankGothic Lt BT", 1, 12), new java.awt.Color(0, 0, 204)));
        PanelDatos2.setOpaque(false);
        PanelDatos2.setLayout(null);

        LNombreProducto1.setFont(new java.awt.Font("Verdana", 1, 12));
        LNombreProducto1.setText("Nombre Producto");
        PanelDatos2.add(LNombreProducto1);
        LNombreProducto1.setBounds(10, 30, 130, 25);

        LNumRuc1.setFont(new java.awt.Font("Verdana", 1, 12));
        LNumRuc1.setText("Categoría");
        PanelDatos2.add(LNumRuc1);
        LNumRuc1.setBounds(365, 30, 64, 25);

        LLote1.setFont(new java.awt.Font("Verdana", 1, 12));
        LLote1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LLote1.setText("Presentación de Lote");
        PanelDatos2.add(LLote1);
        LLote1.setBounds(10, 80, 140, 25);

        TNombreProducto1.setFont(new java.awt.Font("Verdana", 1, 10));
        TNombreProducto1.setForeground(new java.awt.Color(0, 102, 0));
        TNombreProducto1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TNombreProducto1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TNombreProducto1KeyTyped(evt);
            }
        });
        PanelDatos2.add(TNombreProducto1);
        TNombreProducto1.setBounds(160, 30, 190, 25);

        TLote1.setFont(new java.awt.Font("Verdana", 1, 10));
        TLote1.setForeground(new java.awt.Color(0, 102, 0));
        TLote1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TLote1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TLote1KeyTyped(evt);
            }
        });
        PanelDatos2.add(TLote1);
        TLote1.setBounds(160, 80, 190, 25);

        Combocategoria1.setFont(new java.awt.Font("Verdana", 1, 10));
        Combocategoria1.setForeground(new java.awt.Color(0, 102, 0));
        Combocategoria1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hola" }));
        PanelDatos2.add(Combocategoria1);
        Combocategoria1.setBounds(480, 30, 150, 25);

        LPresentacion1.setFont(new java.awt.Font("Verdana", 1, 12));
        LPresentacion1.setText("Detalle Producto");
        PanelDatos2.add(LPresentacion1);
        LPresentacion1.setBounds(365, 80, 110, 25);

        TPresentacion1.setFont(new java.awt.Font("Verdana", 1, 10));
        TPresentacion1.setForeground(new java.awt.Color(0, 102, 0));
        TPresentacion1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TPresentacion1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TPresentacion1KeyTyped(evt);
            }
        });
        PanelDatos2.add(TPresentacion1);
        TPresentacion1.setBounds(480, 80, 150, 25);

        LUnds1.setFont(new java.awt.Font("Verdana", 1, 12));
        LUnds1.setText("Unidades por Lote");
        PanelDatos2.add(LUnds1);
        LUnds1.setBounds(10, 130, 140, 25);

        TUnds1.setFont(new java.awt.Font("Verdana", 1, 10));
        TUnds1.setForeground(new java.awt.Color(0, 102, 0));
        TUnds1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TUnds1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TUnds1KeyTyped(evt);
            }
        });
        PanelDatos2.add(TUnds1);
        TUnds1.setBounds(160, 130, 190, 25);

        BAgregar1.setFont(new java.awt.Font("BankGothic Lt BT", 1, 12));
        BAgregar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        BAgregar1.setText("Agregar");
        BAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAgregar1ActionPerformed(evt);
            }
        });
        PanelDatos2.add(BAgregar1);
        BAgregar1.setBounds(150, 170, 135, 30);

        BActualizar1.setFont(new java.awt.Font("BankGothic Lt BT", 1, 12));
        BActualizar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh16.png"))); // NOI18N
        BActualizar1.setText("Actualizar");
        BActualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BActualizar1ActionPerformed(evt);
            }
        });
        PanelDatos2.add(BActualizar1);
        BActualizar1.setBounds(340, 170, 135, 30);

        LPrecioVta1.setFont(new java.awt.Font("Verdana", 1, 12));
        LPrecioVta1.setText("Precio Venta");
        PanelDatos2.add(LPrecioVta1);
        LPrecioVta1.setBounds(365, 130, 90, 25);

        TPrecioVta1.setFont(new java.awt.Font("Verdana", 1, 10));
        TPrecioVta1.setForeground(new java.awt.Color(0, 102, 0));
        TPrecioVta1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TPrecioVta1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TPrecioVta1KeyTyped(evt);
            }
        });
        PanelDatos2.add(TPrecioVta1);
        TPrecioVta1.setBounds(480, 130, 150, 25);

        Pane1.add(PanelDatos2);
        PanelDatos2.setBounds(10, 10, 640, 210);

        PanelDatos3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Lista de Productos Farmacia \"Allison\"", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("BankGothic Lt BT", 1, 12), new java.awt.Color(0, 0, 204)));
        PanelDatos3.setOpaque(false);
        PanelDatos3.setLayout(null);

        TablaProductos1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TablaProductos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Producto", "Presentación Lote", "Detalle Producto", "Unidades por Lote", "Categoría", "Precio de Venta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaProductos1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        TablaProductos1.setCellSelectionEnabled(true);
        TablaProductos1.setColumnControlVisible(true);
        TablaProductos1.setColumnMargin(10);
        TablaProductos1.setEditable(false);
        TablaProductos1.setFont(new java.awt.Font("Verdana", 0, 10));
        ScrollPane2.setViewportView(TablaProductos1);

        PanelDatos3.add(ScrollPane2);
        ScrollPane2.setBounds(10, 60, 620, 200);

        LblProductos1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblProductos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/titles/ProductosLogo.png"))); // NOI18N
        PanelDatos3.add(LblProductos1);
        LblProductos1.setBounds(0, 0, 630, 60);

        Pane1.add(PanelDatos3);
        PanelDatos3.setBounds(10, 230, 640, 270);

        lblfondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wallpapers/shell_bar.png"))); // NOI18N
        Pane1.add(lblfondo1);
        lblfondo1.setBounds(0, 0, 650, 500);

        TabbedPane1.addTab("Productos", new javax.swing.ImageIcon(getClass().getResource("/images/drugbasket.png")), Pane1); // NOI18N

        TabbedPane1.setBounds(0, 0, 670, 540);
        DesktopProduct1.add(TabbedPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jInternalFrame1.getContentPane().add(DesktopProduct1);
        DesktopProduct1.setBounds(0, 0, 660, 530);

        MenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        MArchivo1.setForeground(new java.awt.Color(51, 102, 0));
        MArchivo1.setText("Archivo");
        MArchivo1.setFont(new java.awt.Font("Papyrus", 1, 12));

        MINuevo1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        MINuevo1.setFont(new java.awt.Font("Papyrus", 1, 12));
        MINuevo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DocumentBlank.png"))); // NOI18N
        MINuevo1.setText("Nuevo Producto");
        MINuevo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MINuevo1ActionPerformed(evt);
            }
        });
        MArchivo1.add(MINuevo1);

        MIDarBaja1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        MIDarBaja1.setFont(new java.awt.Font("Papyrus", 1, 12));
        MIDarBaja1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editdelete.png"))); // NOI18N
        MIDarBaja1.setText("Eliminar Producto del Sistema");
        MIDarBaja1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIDarBaja1ActionPerformed(evt);
            }
        });
        MArchivo1.add(MIDarBaja1);

        MICargos1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        MICargos1.setFont(new java.awt.Font("Papyrus", 1, 12));
        MICargos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/WindowsExplorer.png"))); // NOI18N
        MICargos1.setText("Búsqueda de Producto");
        MICargos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MICargos1ActionPerformed(evt);
            }
        });
        MArchivo1.add(MICargos1);

        MISalir1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        MISalir1.setFont(new java.awt.Font("Papyrus", 1, 12));
        MISalir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Shutdown.png"))); // NOI18N
        MISalir1.setText("Cerrar Módulo");
        MISalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MISalir1ActionPerformed(evt);
            }
        });
        MArchivo1.add(MISalir1);

        MenuBar1.add(MArchivo1);

        getContentPane().add(jInternalFrame1);
        jInternalFrame1.setBounds(0, 0, 57, 31);

        MenuBar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        MArchivo.setForeground(new java.awt.Color(51, 102, 0));
        MArchivo.setText("Archivo");
        MArchivo.setFont(new java.awt.Font("Papyrus", 1, 12));

        MINuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        MINuevo.setFont(new java.awt.Font("Papyrus", 1, 12));
        MINuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DocumentBlank.png"))); // NOI18N
        MINuevo.setText("Nuevo Producto");
        MINuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MINuevoActionPerformed(evt);
            }
        });
        MArchivo.add(MINuevo);

        MIDarBaja.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        MIDarBaja.setFont(new java.awt.Font("Papyrus", 1, 12));
        MIDarBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editdelete.png"))); // NOI18N
        MIDarBaja.setText("Eliminar Producto del Sistema");
        MIDarBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIDarBajaActionPerformed(evt);
            }
        });
        MArchivo.add(MIDarBaja);

        MICargos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        MICargos.setFont(new java.awt.Font("Papyrus", 1, 12));
        MICargos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/WindowsExplorer.png"))); // NOI18N
        MICargos.setText("Búsqueda de Producto");
        MICargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MICargosActionPerformed(evt);
            }
        });
        MArchivo.add(MICargos);

        MISalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        MISalir.setFont(new java.awt.Font("Papyrus", 1, 12));
        MISalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Shutdown.png"))); // NOI18N
        MISalir.setText("Cerrar Módulo");
        MISalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MISalirActionPerformed(evt);
            }
        });
        MArchivo.add(MISalir);

        MenuBar.add(MArchivo);

        setJMenuBar(MenuBar);

        setBounds(150, 20, 669, 587);
    }// </editor-fold>//GEN-END:initComponents

    private void MINuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MINuevoActionPerformed
        CleanObjects();
        CleanComponents();
    }//GEN-LAST:event_MINuevoActionPerformed

    public void CleanObjects()
    {
    setName(null); setLote(null); setDetalle(null); 
    setUnds(null); setPrecioVta(null); setCodProducto(0); setCodCategoria(0);
    BActualizar.setEnabled(true);
    }
    
    public void CleanComponents()
    {
    TNombreProducto.setText(""); TLote.setText(""); TPresentacion.setText("");
    TUnds.setText(""); TPrecioVta.setText(""); Combocategoria.setSelectedIndex(0);
    }
    
    private void MICargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MICargosActionPerformed
        ProductTree ET = new ProductTree();
        DesktopProduct.add(ET);
        ET.setVisible(true);
        ET.setClosable(true);
        ET.setMaximizable(false);
        ET.toFront();
    }//GEN-LAST:event_MICargosActionPerformed

    private void MISalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MISalirActionPerformed
        this.dispose();
        PanelEmperador.HypProductos.setEnabled(true);
    }//GEN-LAST:event_MISalirActionPerformed

    private void TNombreProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TNombreProductoKeyTyped
        char c = evt.getKeyChar();
         if (!((c >= 'a' && c <= 'z') || c == 'ñ' || c == ' '|| c == 'Ñ' || (c >= 'A' && c <= 'Z') || (c == '.') || (c == '-')))
              evt.consume();
}//GEN-LAST:event_TNombreProductoKeyTyped

    private void TLoteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TLoteKeyTyped
        char c = evt.getKeyChar();
        if (!((c >= 'a' && c <= 'z') || c == 'ñ' || c == ' '|| c == 'Ñ' || (c >= 'A' && c <= 'Z')))
            evt.consume();
}//GEN-LAST:event_TLoteKeyTyped

    private void TPresentacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TPresentacionKeyTyped
        // TODO add your handling code here:
}//GEN-LAST:event_TPresentacionKeyTyped

    private void TUndsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TUndsKeyTyped
        char c = evt.getKeyChar();       
        if (!((Character.isDigit(c)) || (c == KeyEvent.VK_BACK_SPACE)))
            evt.consume();
}//GEN-LAST:event_TUndsKeyTyped

    public String getDate()
    {
    String Fecha = null; 
    int dia = 0, mes = 0, año = 0;
    calendar= Calendar.getInstance();
    dia = calendar.get(calendar.DAY_OF_MONTH); mes = calendar.get(calendar.MONTH) + 1; año = calendar.get(calendar.YEAR);
    Fecha = año+"-"+ValidarFecha(dia)+"-"+ValidarFecha(mes);
    return Fecha;
    }
    
    public String ValidarFecha(int fecha)
    {
        String fechavalida = null;
        if(fecha < 10)
            fechavalida = "0"+fecha; 
        else
            fechavalida = String.valueOf(fecha);
        return fechavalida;
    }
    
    private void BAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAgregarActionPerformed

     String NombreProducto = TNombreProducto.getText(); String Lote = TLote.getText();
     String Presentacion = TPresentacion.getText(); String Unds = TUnds.getText();
     String PrecioVta = TPrecioVta.getText();
     
     System.out.print(ConnectProducts.VerifyExistence(TNombreProducto.getText(), TPresentacion.getText()));
    
        
        if(NombreProducto.length() == 0 || Lote.length() == 0 || Presentacion.length() == 0 || Unds.length() == 0 || PrecioVta.length() == 0)
        {
           Utils.MyDialog("Complete todos los datos", "Información del Sistema", "Error.png", "Infected.wav");
        } 
        else 
        {
            if (ConnectProducts.VerifyExistence(TNombreProducto.getText(),TPresentacion.getText()) != null) {
                Utils.MyDialog("Esta producto ya se encuentra en el sistema", "Error al Registrar", "Error.png", "Infected.wav");

            } 
            else 
            {      
              setName(TNombreProducto.getText()); setLote(TLote.getText()); setDetalle(TPresentacion.getText());             
              setUnds(TUnds.getText()); setPrecioVta(TPrecioVta.getText()); setCodCategoria(ConnectProducts.getCodCategory((String.valueOf(Combocategoria.getSelectedItem()))));
              ConnectProducts.SaveDataProducts(CodCategoria, NombreProducto, Lote, DetallePresentacion, Integer.parseInt(UndsContenido), Float.parseFloat(PrecioVta));
            }
     }
}//GEN-LAST:event_BAgregarActionPerformed

    public void setName(String name)
    {
        this.NombreProducto = name;
    }
    public void setLote(String lote)
    {
        this.Lote = lote;
    }
    public void setDetalle(String detalle)
    {
        this.DetallePresentacion = detalle;
    }
     public void setUnds(String unds)
    {
        this.UndsContenido = unds;
    }
     public void setPrecioVta(String precio)
    {
        this.PrecioVta = precio;
    }
     public void setCodCategoria(int codcatego)
    {
        this.CodCategoria = codcatego;
    }
     public static void setCodProducto(int codprodu)
    {
        CodProducto = codprodu;
    }
     private void BActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActualizarActionPerformed
     String NombreProducto = TNombreProducto.getText(); String Lote = TLote.getText();
     String Presentacion = TPresentacion.getText(); String Unds = TUnds.getText();
     String PrecioVta = TPrecioVta.getText();
     
//     System.out.print(ConnectEmployees.VerifyExistence(JFTCedula.getText()));          
        if(NombreProducto.length() == 0 || Lote.length() == 0 || Presentacion.length() == 0 || Unds.length() == 0 || PrecioVta.length() == 0)
        {
          Utils.MyDialog("Complete todos los datos", "Información del Sistema", "Error.png", "Infected.wav");
        } 
        else 
        {     
              setName(TNombreProducto.getText()); setLote(TLote.getText()); setDetalle(TPresentacion.getText());             
              setUnds(TUnds.getText()); setPrecioVta(TPrecioVta.getText()); setCodCategoria(ConnectProducts.getCodCategory((String.valueOf(Combocategoria.getSelectedItem()))));
              ConnectProducts.ModifyDataProducts(CodProducto,CodCategoria, NombreProducto, Lote, DetallePresentacion, Integer.parseInt(UndsContenido), getDate(), Float.parseFloat(PrecioVta));       
        }  
       
}//GEN-LAST:event_BActualizarActionPerformed

    private void TPrecioVtaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TPrecioVtaKeyTyped
        char c = evt.getKeyChar();
       
        if (!((Character.isDigit(c)) || (c == KeyEvent.VK_BACK_SPACE) || (c == '.')))
            evt.consume();
}//GEN-LAST:event_TPrecioVtaKeyTyped

    private void MIDarBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIDarBajaActionPerformed
        DeleteProduct JD = new DeleteProduct();
       DesktopProduct.add(JD);
       JD.setVisible(true);
       JD.setClosable(true);
       JD.setMaximizable(false);
       JD.toFront();
}//GEN-LAST:event_MIDarBajaActionPerformed

    private void TNombreProducto1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TNombreProducto1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TNombreProducto1KeyTyped

    private void TLote1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TLote1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TLote1KeyTyped

    private void TPresentacion1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TPresentacion1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TPresentacion1KeyTyped

    private void TUnds1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TUnds1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TUnds1KeyTyped

    private void BAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAgregar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BAgregar1ActionPerformed

    private void BActualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActualizar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BActualizar1ActionPerformed

    private void TPrecioVta1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TPrecioVta1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TPrecioVta1KeyTyped

    private void MINuevo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MINuevo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MINuevo1ActionPerformed

    private void MIDarBaja1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIDarBaja1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MIDarBaja1ActionPerformed

    private void MICargos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MICargos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MICargos1ActionPerformed

    private void MISalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MISalir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MISalir1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton BActualizar;
    public static javax.swing.JButton BActualizar1;
    private javax.swing.JButton BAgregar;
    private javax.swing.JButton BAgregar1;
    public static javax.swing.JComboBox Combocategoria;
    public static javax.swing.JComboBox Combocategoria1;
    private javax.swing.JDesktopPane DesktopProduct;
    private javax.swing.JDesktopPane DesktopProduct1;
    private javax.swing.JLabel LLote;
    private javax.swing.JLabel LLote1;
    private javax.swing.JLabel LNombreProducto;
    private javax.swing.JLabel LNombreProducto1;
    private javax.swing.JLabel LNumRuc;
    private javax.swing.JLabel LNumRuc1;
    private javax.swing.JLabel LPrecioVta;
    private javax.swing.JLabel LPrecioVta1;
    private javax.swing.JLabel LPresentacion;
    private javax.swing.JLabel LPresentacion1;
    private javax.swing.JLabel LUnds;
    private javax.swing.JLabel LUnds1;
    private javax.swing.JLabel LblProductos;
    private javax.swing.JLabel LblProductos1;
    private javax.swing.JMenu MArchivo;
    private javax.swing.JMenu MArchivo1;
    private javax.swing.JMenuItem MICargos;
    private javax.swing.JMenuItem MICargos1;
    private javax.swing.JMenuItem MIDarBaja;
    private javax.swing.JMenuItem MIDarBaja1;
    private javax.swing.JMenuItem MINuevo;
    private javax.swing.JMenuItem MINuevo1;
    private javax.swing.JMenuItem MISalir;
    private javax.swing.JMenuItem MISalir1;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuBar MenuBar1;
    private javax.swing.JPanel Pane0;
    private javax.swing.JPanel Pane1;
    private javax.swing.JPanel PanelDatos;
    private javax.swing.JPanel PanelDatos1;
    private javax.swing.JPanel PanelDatos2;
    private javax.swing.JPanel PanelDatos3;
    private javax.swing.JScrollPane ScrollPane1;
    private javax.swing.JScrollPane ScrollPane2;
    public static javax.swing.JTextField TLote;
    public static javax.swing.JTextField TLote1;
    public static javax.swing.JTextField TNombreProducto;
    public static javax.swing.JTextField TNombreProducto1;
    public static javax.swing.JTextField TPrecioVta;
    public static javax.swing.JTextField TPrecioVta1;
    public static javax.swing.JTextField TPresentacion;
    public static javax.swing.JTextField TPresentacion1;
    public static javax.swing.JTextField TUnds;
    public static javax.swing.JTextField TUnds1;
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JTabbedPane TabbedPane1;
    public static org.jdesktop.swingx.JXTable TablaProductos;
    public static org.jdesktop.swingx.JXTable TablaProductos1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel lblfondo;
    private javax.swing.JLabel lblfondo1;
    // End of variables declaration//GEN-END:variables
    
}
